#! /bin/bash
#SBATCH -p q_student
#SBATCH -N 36
#SBATCH --ntasks-per-node 32
#SBATCH --cpu-freq=High
#SBATCH --time=3:00

num_nodes=$1
procs_p_node=$2
algo_num=$3
op=$4
typ=$5
algo_name=$6
block_size=$7

echo "running on $1 nodes with $2 processes per node"

srun ../bin/benchmark ../results/results_${num_nodes}_${procs_p_node}_${algo_name}_${op}_${typ}_${block_size}.csv $num_nodes $procs_p_node $algo_num $block_size

